import os
from dotenv import load_dotenv

load_dotenv()  # take environment variables from .env.

URL = os.getenv('URL', 'localhost:5000')
APSCHEDULER_YEAR = os.getenv("APSCHEDULER_YEAR", None)
APSCHEDULER_MONTH = os.getenv("APSCHEDULER_MONTH", None)
APSCHEDULER_DAY = os.getenv("APSCHEDULER_DAY", None)
APSCHEDULER_WEEK = os.getenv("APSCHEDULER_WEEK", None)
APSCHEDULER_DAY_OF_WEEK = os.getenv("APSCHEDULER_DAY_OF_WEEK", None)
APSCHEDULER_HOUR = os.getenv("APSCHEDULER_HOUR", None)
APSCHEDULER_MINUTE = os.getenv("APSCHEDULER_MINUTE", None)
APSCHEDULER_SECOND = os.getenv("APSCHEDULER_SECOND", None)


APSCHEDULER_YEAR = None if APSCHEDULER_YEAR is None else str(APSCHEDULER_YEAR)
APSCHEDULER_MONTH = None if APSCHEDULER_MONTH is None else str(APSCHEDULER_MONTH)
APSCHEDULER_DAY = None if APSCHEDULER_DAY is None else str(APSCHEDULER_DAY)
APSCHEDULER_WEEK = None if APSCHEDULER_WEEK is None else str(APSCHEDULER_WEEK)
APSCHEDULER_DAY_OF_WEEK = None if APSCHEDULER_DAY_OF_WEEK is None else str(APSCHEDULER_DAY_OF_WEEK)
APSCHEDULER_HOUR = None if APSCHEDULER_HOUR is None else str(APSCHEDULER_HOUR)
APSCHEDULER_MINUTE = None if APSCHEDULER_MINUTE is None else str(APSCHEDULER_MINUTE)
APSCHEDULER_SECOND = None if APSCHEDULER_SECOND is None else str(APSCHEDULER_SECOND)